[tool.black]
line-length = 88
target-version = ["py312"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_defs = false

[tool.flake8]
max-line-length = 120
extend-ignore = [
    "E501",  # ignore lignes trop longues
    "F401",  # ignore imports non utilisés
    "E402",  # ignore imports pas en haut du fichier
]
